### ISSUE TITLE
Cannot download data

### ISSUE THREAD

**Issue by yangsenwxy** [michalkoziarski/DiagSet#2]
Hi,
   Thank you very much for releasing such a great database. I believe it can promote the progress of prostate pathology.
   But I have encountered some problems. I cannot download the DiagSet-B data set. It will report an error and show that it does not exist. Can you help me?

Thanks
Sen

**Comment by michalkoziarski** [comment]
Hi Sen,

sorry for a long delay, FYI the scans in DiagSet-B should be accessible again. In case of any further issues feel free to let me know, or alternatively let the site admin know - his contact info is available at https://ai-econsilio.diag.pl/contact, he might be able to address your issue faster than me.

Best,
Michał

**Comment by yangsenwxy** [comment]
Dear Michał，
          I can not still download the DiagSet-B data set. Can you help me?
Thanks
Sen
