### ISSUE TITLE
Can not download the data

### ISSUE THREAD

**Issue by ZXXu96** [michalkoziarski/DiagSet#3]
Hello,

Would you please check the link provided in the paper? 
It shows 'The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.' when I try to access the site.

Thank you!

**Comment by michalkoziarski** [comment]
Could you please check if the issue is still present? I believe there was some downtime yesterday due to certificate change, but at least on our end it seems to work.

**Comment by ZXXu96** [comment]
I can now access this site. Thank you!
