### ISSUE TITLE
Can not download the data

### ISSUE THREAD

**Issue by nelxnoemi** [michalkoziarski/DiagSet#4]
Hello,

Would you please check the link provided in the paper? I am also unable to access the link due to it showing 'The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.' when I try to access the site.
I would need this ASAP, so hope to hear from you soon.

Thank you!

**Comment by michalkoziarski** [comment]
Hi, sorry about that - I passed the information to the company responsible for hosting the website.

**Comment by michalkoziarski** [comment]
FYI, they were aware of the issue and are working on fixing it.

**Comment by michalkoziarski** [comment]
@nelxnoemi I believe the website should be back up.

**Comment by nelxnoemi** [comment]
@michalkoziarski Hai, tq for the notify. I am able to access it now.

**Comment by undercutspiky** [comment]
@nelxnoemi The website seems to be down again. I simply don't get a response from the website at all ("This site can’t be reached").

**Comment by michalkoziarski** [comment]
@undercutspiky did you try emailing the administrator of the website, as in README? We are not responsible for hosting the website, and not affiliated with the company doing it anymore, so we'd simply be passing your message along; if you haven't, please email them directly first.

**Comment by undercutspiky** [comment]
@michalkoziarski Yes, I've done that but maybe the admin is on Christmas + New year vacation. I'll wait for a response from them.
