### ISSUE TITLE
Unable to access the website. 

### ISSUE THREAD

**Issue by ashwin-acharya01** [michalkoziarski/DiagSet#6]
I'm trying to access the website - https://ai-econsilio.diag.pl mentioned in the paper and on the GitHub readme for accessing the dataset. But the mentioned URL doesn't work. I wanted to know whether there were any changes in the address or anything else. Any help would be greatly appreciated.

Regards 
Ashwin

**Comment by michalkoziarski** [comment]
Sorry about this, I received a reply from the website administrator saying that they have to make some upgrades to it and it should be back online soon.

**Comment by michalkoziarski** [comment]
@ashwin-acharya01 FYI, it's online again, sorry for the delay.
